### ISSUE TITLE
Count parameter

### ISSUE THREAD

**Issue by pabloegpf1** [PawelPleskaczynski/apod_api#2]
Hi! first of all congratulations on this project, it's so convenient compared to Nasa's. I am now using it for a school project.
However the only thing it does not have is a ?count parameter so we can get several pictures at a time. Is this something you would be willing to introduce?
Thank you

**Comment by PawelPleskaczynski** [comment]
Hi, thanks for choosing this API! :smiley: 
I have added this feature, it's error resistant (I don't know if NASA's `count` parameter is resistant for not existing APODs, probably not), it will always return requested number of APODs, if there's not any APOD for randomly chosen date, another date is returned instead.
